// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/f318fbd33149ef0921b84657996ad31dab1e3241/react-fa/react-fa.d.ts
declare module "react-fa" {
	import {ComponentClass, Props} from 'react';

	interface IconProps extends Props<Icon> {
		name:string;
		className?:string;
		size?:string;
		spin?:boolean;
		rotate?:string;
		flip?:string;
		fixedWidth?:boolean;
		pulse?:boolean;
		stack?:string;
		inverse?:boolean;
	}

	interface Icon extends ComponentClass<IconProps> {}
	export const Icon:Icon;
}